### ISSUE TITLE
Include past COSC core members in about page

### ISSUE THREAD

**Issue by r0mflip** [cbitosc/cbitosc.github.io#10]
about page has a backlog that needs to be done. Past COSC teams needs to be included in it. Have a look at https://github.com/orgs/cbitosc/teams and include links.

**Comment by notlmn** [comment]
Refer to https://github.com/cbitosc/cbitosc.github.io/issues/33#issue-580782356 on exact changes.

**Comment by vihar** [comment]
Can someone look into this? Thanks.

**Comment by gopalM-3** [comment]
Added both the teams and the site has been successfully updated; however, the team images are missing. To enhance the visual appeal and provide a more personalized touch, it is necessary to add appropriate team member images. Cheers!
