### ISSUE TITLE
Lazyload all images

### ISSUE THREAD

**Issue by r0mflip** [cbitosc/cbitosc.github.io#14]
Add lazy loading to all below the fold images making sure the layout doesn't break. Refer to https://css-tricks.com/native-lazy-loading/

**Comment by coderwassananmol** [comment]
Would like to take it.

**Comment by mora50** [comment]
I'd like to try

**Comment by mora50** [comment]
@r0mflip Can i use javascript to make the lazy load?, it can be more compatible with all browsers/mobile
