### ISSUE TITLE
Changes Needed.

### ISSUE THREAD

**Issue by RohithSrk** [cbitosc/cbitosc.github.io#3]
- [ ] Add **About Us**, **Contact Us,** **FAQs** & **Projects** pages.
- [ ] Move team members to **About Us** page.
- [ ] Link events to their respective event pages.
- [ ] The footer should include links to all pages and one main link to the college website.
- [ ] Add a link to the medium blog in the main menu.

**Comment by r0mflip** [comment]
Being tracked at #4
