### ISSUE TITLE
Cleanup README

### ISSUE THREAD

**Issue by r0mflip** [cbitosc/cbitosc.github.io#8]
Current readme is stale, update it to reflect the changes from #6

**Comment by kushaggarwal** [comment]
I would like to work on this
Can you please help what details would you like to have in the readme

**Comment by r0mflip** [comment]
@kushaggarwal Mostly a small writeup from the site, can remove existing thing totally.

**Comment by kushaggarwal** [comment]
So basically reflecting the basic purpose and important things from your site right?

**Comment by r0mflip** [comment]
> So basically reflecting the basic purpose and important things from your site right?

Yes.

**Comment by kushaggarwal** [comment]
Okay surely I will work on this
